from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

HOOK_TEMPLATE = """#!/usr/bin/env python3
\"\"\"Code Agent pre-commit hook. Generated by code-agent.\"\"\"
import subprocess, sys, json, os

def main():
    repo_root = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True
    ).stdout.strip()

    if not repo_root:
        sys.exit(0)

    # Get staged files
    result = subprocess.run(
        ["git", "diff", "--cached", "--name-only"],
        capture_output=True, text=True, cwd=repo_root
    )
    if result.returncode != 0:
        print("code-agent: could not get staged files")
        sys.exit(1)

    files = [f for f in result.stdout.strip().split("\\n") if f.strip()]
    if not files:
        sys.exit(0)

    # Check supported extensions
    exts = {{".py", ".js", ".ts", ".jsx", ".tsx", ".rs", ".go", ".java"}}
    supported = [f for f in files if Path(f).suffix in exts]

    if not supported:
        sys.exit(0)

    print(f"code-agent: reviewing {len(supported)} staged files...")

    for f in supported:
        review = subprocess.run(
            [sys.executable, "-m", "code_agent", "review", f],
            capture_output=True, text=True, cwd=repo_root
        )
        if review.stdout:
            print(review.stdout[:500])
        if review.returncode != 0:
            print(f"code-agent: review issues in {f}")
            # Non-blocking by default

    sys.exit(0)

if __name__ == "__main__":
    main()
"""


def install_hook(repo_root: str | None = None, hook_type: str = "pre-commit") -> dict[str, Any]:
    if repo_root is None:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            return {"success": False, "error": "Not a git repository"}
        repo_root = result.stdout.strip()

    hooks_dir = Path(repo_root) / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    hook_path = hooks_dir / hook_type
    hook_path.write_text(HOOK_TEMPLATE)
    hook_path.chmod(0o755)

    return {"success": True, "message": f"Installed {hook_type} hook at {hook_path}"}


def remove_hook(hook_type: str = "pre-commit") -> dict[str, Any]:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        return {"success": False, "error": "Not a git repository"}

    hook_path = Path(result.stdout.strip()) / ".git" / "hooks" / hook_type
    if hook_path.exists():
        hook_path.unlink()
        return {"success": True, "message": f"Removed {hook_type} hook"}
    return {"success": False, "error": f"No {hook_type} hook found"}
