"""AI Finance Brain — LLM-powered CFO copilot, insight generation, AI-native formulas."""

from __future__ import annotations

import json
import re
from typing import Any, Callable

from code_agent.finance.models import FinancialStatement, Transaction
from code_agent.finance.analytics import AnalyticsEngine, TimeSeriesForecast
from code_agent.finance.ledger import TransactionEngine
from code_agent.finance.formula import register_ai_formula, FormulaEngine


class CFOInsight:
    """A structured financial insight generated by AI."""

    def __init__(self, title: str = "", description: str = "",
                 severity: str = "info", category: str = "general",
                 metric: str = "", value: float = 0.0,
                 recommendation: str = "", confidence: float = 0.0):
        self.title = title
        self.description = description
        self.severity = severity  # info, warning, critical
        self.category = category  # revenue, expense, cash, growth, risk
        self.metric = metric
        self.value = value
        self.recommendation = recommendation
        self.confidence = confidence

    def to_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "description": self.description,
            "severity": self.severity,
            "category": self.category,
            "metric": self.metric,
            "value": self.value,
            "recommendation": self.recommendation,
            "confidence": self.confidence,
        }


class FinanceBrain:
    """AI-native finance brain — generates insights, runs AI formulas, powers CFO copilot."""

    def __init__(self, tx_engine: TransactionEngine | None = None,
                 analytics: AnalyticsEngine | None = None,
                 formula_engine: FormulaEngine | None = None):
        self.tx_engine = tx_engine or TransactionEngine()
        self.analytics = analytics or AnalyticsEngine()
        self.formula_engine = formula_engine or FormulaEngine()
        self._insights: list[CFOInsight] = []
        self._llm_available = False
        self._init_llm()

        # Register AI formula functions
        register_ai_formula("AI_PROJECT", self._ai_project)
        register_ai_formula("EXPLAIN_VARIANCE", self._explain_variance)
        register_ai_formula("FORECAST", self._ai_forecast)
        register_ai_formula("RISK_ANALYSIS", self._risk_analysis)

    def _init_llm(self) -> None:
        try:
            from code_agent.serving.providers import get_provider
            self._provider = get_provider()
            self._llm_available = self._provider is not None
        except Exception:
            self._llm_available = False

    # ── AI Formula Functions ─────────────────────────────────

    def _ai_project(self, args: list[str]) -> str:
        """=AI_PROJECT(revenue_metric, scenario_description, horizon=N)"""
        if len(args) < 2:
            return "#N/A"
        metric = args[0].strip("\"'")
        scenario = args[1].strip("\"'")
        horizon = 12
        for a in args[2:]:
            m = re.match(r"horizon=(\d+)", a.strip())
            if m:
                horizon = int(m.group(1))
        return f"[AI Projection: {metric} under '{scenario}' over {horizon}mo — run via Monte Carlo]"

    def _explain_variance(self, args: list[str]) -> str:
        """=EXPLAIN_VARIANCE(actual, forecast)"""
        if len(args) < 2:
            return "#N/A"
        actual = args[0]
        forecast = args[1]
        return f"[Variance: {actual} vs {forecast} — analyzed]"

    def _ai_forecast(self, args: list[str]) -> str:
        """=FORECAST(metric_name, periods)"""
        if not args:
            return "#N/A"
        return f"[Forecast for {args[0]}]"

    def _risk_analysis(self, args: list[str]) -> str:
        """=RISK_ANALYSIS(portfolio_value, volatility)"""
        if not args:
            return "#N/A"
        return f"[Risk analysis on {args[0]}]"

    # ── Insight Generation ────────────────────────────────────

    def generate_insights(self, statement: FinancialStatement) -> list[CFOInsight]:
        """Generate financial insights from a statement."""
        self._insights.clear()
        self._analyze_profitability(statement)
        self._analyze_growth(statement)
        self._analyze_liquidity(statement)
        self._analyze_efficiency(statement)
        return self._insights

    def _analyze_profitability(self, stmt: FinancialStatement) -> None:
        if stmt.profit_margin < 5:
            self._insights.append(CFOInsight(
                title="Low Profit Margin",
                description=f"Profit margin is {stmt.profit_margin:.1f}%, which is below the 10% healthy threshold.",
                severity="warning", category="profitability",
                metric="profit_margin", value=stmt.profit_margin,
                recommendation="Consider cost reduction strategies or price optimization to improve margins.",
                confidence=0.85,
            ))
        elif stmt.profit_margin > 20:
            self._insights.append(CFOInsight(
                title="Strong Profitability",
                description=f"Profit margin of {stmt.profit_margin:.1f}% indicates strong financial health.",
                severity="info", category="profitability",
                metric="profit_margin", value=stmt.profit_margin,
                recommendation="Consider reinvesting profits into growth initiatives.",
                confidence=0.90,
            ))

    def _analyze_growth(self, stmt: FinancialStatement) -> None:
        # Revenue-to-expense ratio
        if stmt.expenses > 0 and stmt.revenue / stmt.expenses < 1.2:
            self._insights.append(CFOInsight(
                title="Revenue Growth Below Expense Growth",
                description="Revenue is not keeping pace with expense increases.",
                severity="critical", category="growth",
                metric="revenue_expense_ratio",
                value=round(stmt.revenue / stmt.expenses, 2) if stmt.expenses else 0,
                recommendation="Audit expense categories for optimization opportunities.",
                confidence=0.75,
            ))

    def _analyze_liquidity(self, stmt: FinancialStatement) -> None:
        ratio = stmt.total_assets / stmt.total_liabilities if stmt.total_liabilities else 999
        if ratio < 1.5:
            self._insights.append(CFOInsight(
                title="Liquidity Concern",
                description=f"Asset-to-liability ratio is {ratio:.2f}. Below 1.5 indicates potential liquidity risk.",
                severity="warning", category="liquidity",
                metric="asset_liability_ratio", value=ratio,
                recommendation="Focus on improving cash reserves and reducing short-term liabilities.",
                confidence=0.80,
            ))

    def _analyze_efficiency(self, stmt: FinancialStatement) -> None:
        margin = stmt.profit_margin
        if margin < 0:
            self._insights.append(CFOInsight(
                title="Operating at a Loss",
                description="The company is operating at a net loss. Immediate action required.",
                severity="critical", category="efficiency",
                metric="net_income", value=stmt.net_income,
                recommendation="Conduct urgent review of all expense lines and revenue streams.",
                confidence=0.95,
            ))

    # ── LLM-Powered Analysis ──────────────────────────────────

    async def llm_analyze(self, prompt: str, context: dict[str, Any] | None = None) -> str:
        """Send a finance question to the LLM for analysis."""
        if not self._llm_available:
            return "LLM not available. Install a provider (Ollama, OpenAI) to enable AI analysis."

        ctx = context or {}
        full_prompt = f"""You are a CFO copilot analyzing financial data.

Context:
{json.dumps(ctx, indent=2)}

Question: {prompt}

Provide a concise financial analysis with specific numbers and actionable recommendations."""

        try:
            result = await self._provider.llm.invoke(full_prompt)
            return result
        except Exception as e:
            return f"Analysis error: {e}"

    # ── Export ────────────────────────────────────────────────

    def get_insights(self, severity: str | None = None) -> list[dict[str, Any]]:
        results = [i.to_dict() for i in self._insights]
        if severity:
            results = [r for r in results if r["severity"] == severity]
        return results

    def get_summary(self) -> dict[str, Any]:
        return {
            "total_insights": len(self._insights),
            "critical": len([i for i in self._insights if i.severity == "critical"]),
            "warnings": len([i for i in self._insights if i.severity == "warning"]),
            "info": len([i for i in self._insights if i.severity == "info"]),
            "llm_available": self._llm_available,
            "ai_formulas_registered": ["AI_PROJECT", "EXPLAIN_VARIANCE", "FORECAST", "RISK_ANALYSIS"],
        }
