"""
Professional disclaimer injection for AI output.

Every AI response in a regulated context carries a mandatory disclaimer.
Injected at the API boundary — the frontend never has to remember to add it.

Regulation basis:
  Healthcare: FDA guidance on AI/ML-based SaMD; AMA policy on AI in medicine
  Legal:      Model Rules of Professional Conduct 1.1 (competence); state bar rules
  Finance:    SEC Rule 206(4)-1 (investment adviser marketing); FINRA Rule 2210
"""
from __future__ import annotations

DISCLAIMERS: dict[str, str] = {
    "healthcare": (
        "⚕ This AI output is for informational purposes only and does not constitute "
        "medical advice, diagnosis, or treatment. Always consult a licensed healthcare "
        "professional before making clinical decisions. Orchestra AI does not replace "
        "physician judgment."
    ),
    "legal": (
        "⚖ This AI output is for informational purposes only and does not constitute "
        "legal advice or create an attorney-client relationship. Laws vary by jurisdiction "
        "and fact pattern. Always consult a licensed attorney before acting on any legal "
        "information."
    ),
    "finance": (
        "📊 This AI output is for informational and educational purposes only. It does not "
        "constitute investment advice, a solicitation, or an offer to buy or sell any "
        "security. Past performance is not indicative of future results. Consult a "
        "registered investment adviser before making investment decisions."
    ),
    "general": (
        "ℹ This response was generated by an AI model. While we strive for accuracy, "
        "AI can make mistakes. Verify important information from authoritative sources."
    ),
}

# Route prefix → vertical mapping
_ROUTE_VERTICAL: dict[str, str] = {
    "/api/healthcare":    "healthcare",
    "/api/legal":         "legal",
    "/api/finance":       "finance",
    "/api/legal/brain":   "legal",
    "/api/finance/brain": "finance",
    "/v1/query":          "general",
    "/v1/run":            "general",
}


def disclaimer_for_path(path: str) -> str | None:
    """Return the appropriate disclaimer for an API path, or None."""
    for prefix, vertical in _ROUTE_VERTICAL.items():
        if path.startswith(prefix):
            return DISCLAIMERS.get(vertical)
    return None


def disclaimer_for_vertical(vertical: str) -> str:
    return DISCLAIMERS.get(vertical, DISCLAIMERS["general"])


def inject_disclaimer(response_body: dict, path: str) -> dict:
    """
    Add a _disclaimer key to a JSON response dict if the path warrants one.
    Only injected when the response contains an "ai" field pattern.
    """
    d = disclaimer_for_path(path)
    if d and _looks_like_ai_response(response_body):
        response_body["_disclaimer"] = d
    return response_body


def _looks_like_ai_response(body: dict) -> bool:
    """Heuristic: does this response contain AI-generated text?"""
    ai_keys = {"response", "content", "answer", "result", "draft", "analysis",
                "summary", "recommendation", "output", "insights"}
    if isinstance(body, dict):
        top_keys = set(body.keys())
        if top_keys & ai_keys:
            return True
        # Check nested data envelope
        data = body.get("data", {})
        if isinstance(data, dict) and set(data.keys()) & ai_keys:
            return True
    return False


# ── ASGI middleware version (injects into JSON responses) ────────────────────

class DisclaimerMiddleware:
    """
    ASGI middleware that appends professional disclaimers to AI API responses.
    Only fires on /api/* and /v1/* JSON responses that look like AI output.
    """
    import json as _json

    def __init__(self, app) -> None:
        self.app = app

    async def __call__(self, scope, receive, send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        path = scope.get("path", "")
        # Only process API paths that might have AI output
        if not (path.startswith("/api/") or path.startswith("/v1/")):
            await self.app(scope, receive, send)
            return

        disclaimer = disclaimer_for_path(path)
        if not disclaimer:
            await self.app(scope, receive, send)
            return

        import json
        content_type = ""
        body_chunks: list[bytes] = []

        async def patched_send(message):
            nonlocal content_type

            if message["type"] == "http.response.start":
                for name, value in message.get("headers", []):
                    if name.lower() == b"content-type":
                        content_type = value.decode("utf-8", errors="replace")
                        break
                await send(message)

            elif message["type"] == "http.response.body":
                body = message.get("body", b"")
                more = message.get("more_body", False)

                if "application/json" in content_type:
                    body_chunks.append(body)
                    if not more:
                        full = b"".join(body_chunks)
                        try:
                            data = json.loads(full)
                            if _looks_like_ai_response(data):
                                data["_disclaimer"] = disclaimer
                                full = json.dumps(data).encode("utf-8")
                        except Exception:
                            pass
                        await send({"type": "http.response.body", "body": full, "more_body": False})
                else:
                    await send(message)
            else:
                await send(message)

        await self.app(scope, receive, patched_send)
