from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class ProfessionalDisclaimer:
    domain: str = ""
    title: str = ""
    body: str = ""
    severity: str = "informational"


DISCLAIMERS: dict[str, list[ProfessionalDisclaimer]] = {
    "healthcare": [
        ProfessionalDisclaimer(
            domain="healthcare",
            title="Not a substitute for professional medical advice",
            body="This AI-generated output is for informational and reference purposes only. "
                 "It does not constitute medical advice, diagnosis, or treatment. "
                 "Always consult a qualified healthcare provider for clinical decisions.",
            severity="warning",
        ),
        ProfessionalDisclaimer(
            domain="healthcare",
            title="Clinical decision support disclaimer",
            body="AI-generated clinical suggestions must be reviewed by a licensed "
                 "practitioner before any patient care action is taken. "
                 "The clinician retains full responsibility for all treatment decisions.",
            severity="critical",
        ),
        ProfessionalDisclaimer(
            domain="healthcare",
            title="HIPAA compliance notice",
            body="Ensure all patient data entered complies with HIPAA Privacy and "
                 "Security Rules. Do not enter more PHI than necessary for the task. "
                 "All PHI is encrypted at rest.",
            severity="informational",
        ),
    ],
    "legal": [
        ProfessionalDisclaimer(
            domain="legal",
            title="Not a substitute for legal advice",
            body="This AI-generated content is for informational purposes only and "
                 "does not constitute legal advice or create an attorney-client "
                 "relationship. Consult a licensed attorney for legal matters.",
            severity="warning",
        ),
        ProfessionalDisclaimer(
            domain="legal",
            title="Attorney review required",
            body="All AI-generated legal documents must be reviewed and approved "
                 "by a licensed attorney before use. The reviewing attorney "
                 "bears full responsibility for the final content.",
            severity="critical",
        ),
    ],
    "financial": [
        ProfessionalDisclaimer(
            domain="financial",
            title="Not financial advice",
            body="This AI-generated output is for informational purposes only and "
                 "does not constitute financial advice, investment recommendations, "
                 "or solicitation. Consult a qualified financial advisor for "
                 "investment decisions.",
            severity="warning",
        ),
        ProfessionalDisclaimer(
            domain="financial",
            title="Regulatory compliance notice",
            body="All financial transactions and recommendations generated by this "
                 "system are subject to applicable regulations including but not "
                 "limited to SEC, FINRA, and SOX requirements.",
            severity="informational",
        ),
    ],
    "general": [
        ProfessionalDisclaimer(
            domain="general",
            title="AI-generated content",
            body="This content was generated by an AI system and may contain errors. "
                 "Verify all information before acting on it.",
            severity="informational",
        ),
    ],
}


class DisclaimerSystem:
    """Manages and appends professional disclaimers to AI-generated output.

    Domain-specific disclaimers are automatically attached based on
    the agent's professional context (healthcare, legal, financial).
    """

    def __init__(self) -> None:
        self._custom: dict[str, list[ProfessionalDisclaimer]] = {}

    def get_disclaimers(self, domain: str) -> list[ProfessionalDisclaimer]:
        result = list(DISCLAIMERS.get(domain, []))
        result.extend(self._custom.get(domain, []))
        return result

    def add_disclaimer(self, domain: str, disclaimer: ProfessionalDisclaimer) -> None:
        self._custom.setdefault(domain, []).append(disclaimer)

    def append_to_output(self, domain: str, output: str) -> str:
        disclaimers = self.get_disclaimers(domain)
        if not disclaimers:
            return output
        footer = "\n\n---\n"
        for d in disclaimers:
            if d.severity == "critical":
                footer += f"\n**{d.title}**\n{d.body}\n"
            elif d.severity == "warning":
                footer += f"\n*{d.title}*: {d.body}\n"
            else:
                footer += f"\n{d.body}\n"
        return output + footer

    def list_domains(self) -> list[str]:
        domains = set(DISCLAIMERS.keys())
        domains.update(self._custom.keys())
        return sorted(domains)
