from __future__ import annotations

import json
from pathlib import Path
from typing import Any


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: system-ui, -apple-system, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }}
nav {{ position: fixed; left: 0; top: 0; width: 260px; height: 100vh; background: #161b22; border-right: 1px solid #30363d; padding: 1rem; overflow-y: auto; }}
nav h2 {{ color: #58a6ff; margin-bottom: 1rem; font-size: 1rem; text-transform: uppercase; letter-spacing: 0.05em; }}
nav a {{ display: block; color: #8b949e; text-decoration: none; padding: 0.3rem 0.5rem; border-radius: 4px; font-size: 0.85rem; }}
nav a:hover {{ background: #1c2333; color: #58a6ff; }}
main {{ margin-left: 260px; padding: 2rem 3rem; max-width: 900px; }}
h1 {{ color: #58a6ff; margin-bottom: 1rem; }}
h2 {{ color: #c9d1d9; margin: 1.5rem 0 0.5rem; border-bottom: 1px solid #30363d; padding-bottom: 0.3rem; }}
p {{ margin: 0.5rem 0; }}
code {{ background: #161b22; padding: 0.2rem 0.4rem; border-radius: 3px; font-size: 0.9em; }}
pre {{ background: #161b22; padding: 1rem; border-radius: 6px; overflow-x: auto; margin: 0.5rem 0; }}
.module {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; margin: 0.5rem 0; }}
.module h3 {{ color: #58a6ff; }}
.footer {{ margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #30363d; color: #8b949e; font-size: 0.85rem; }}
</style>
</head>
<body>
<nav>
<h2>{nav_title}</h2>
{nav_links}
</nav>
<main>
{content}
<div class="footer">Generated by Code Agent</div>
</main>
</body>
</html>"""


class DocsSiteBuilder:
    """Build a self-hosted documentation site from codebase modules."""

    def __init__(self, output_dir: str = "docs-site"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def build(self, source_path: str = ".") -> list[str]:
        generated = []

        # Index page
        index = self._build_index(source_path)
        (self.output_dir / "index.html").write_text(index, encoding="utf-8")
        generated.append("index.html")

        # Module pages
        modules_dir = Path(source_path)
        for f in sorted(modules_dir.rglob("**/*.py")):
            if f.name.startswith("_"):
                continue
            rel = f.relative_to(modules_dir)
            page = self._build_module_page(f)
            out_path = self.output_dir / rel.with_suffix(".html")
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(page, encoding="utf-8")
            generated.append(str(rel.with_suffix(".html")))

        return generated

    def _build_index(self, source_path: str) -> str:
        modules_dir = Path(source_path)
        modules = sorted(modules_dir.rglob("**/*.py"))
        nav_links = '<a href="index.html">Home</a>\n'
        content_parts = ["<h1>Code Agent Documentation</h1>",
                        "<p>Welcome to the auto-generated documentation site.</p>",
                        f"<h2>Modules ({len(modules)})</h2>"]

        for m in modules:
            if m.name.startswith("_"):
                continue
            rel = m.relative_to(modules_dir)
            html_path = rel.with_suffix(".html")
            nav_links += f'<a href="{html_path}">{rel}</a>\n'
            content_parts.append(
                f'<div class="module"><h3><a href="{html_path}">{rel}</a></h3>'
                f"<p>{m.stat().st_size} bytes</p></div>"
            )

        return HTML_TEMPLATE.format(
            title="Code Agent Docs",
            nav_title="Modules",
            nav_links=nav_links,
            content="\n".join(content_parts),
        )

    def _build_module_page(self, file_path: Path) -> str:
        content = file_path.read_text(encoding="utf-8", errors="ignore")
        rel = str(file_path.relative_to(file_path.parent.parent.parent) if file_path.parent.parent.parent else file_path.name)

        nav_links = '<a href="../index.html">Home</a>\n'
        page_content = [
            f"<h1>{rel}</h1>",
            f"<p><strong>Path:</strong> {file_path}</p>",
            f"<p><strong>Size:</strong> {file_path.stat().st_size} bytes</p>",
            f"<h2>Source</h2>",
            f"<pre><code>{content[:5000].replace('<', '&lt;').replace('>', '&gt;')}</code></pre>",
        ]
        if len(content) > 5000:
            page_content.append("<p><em>(Source truncated to 5000 chars)</em></p>")

        return HTML_TEMPLATE.format(
            title=f"Module: {rel}",
            nav_title="Navigation",
            nav_links=nav_links,
            content="\n".join(page_content),
        )

    def serve(self, host: str = "127.0.0.1", port: int = 8300) -> None:
        """Serve the docs site via HTTP."""
        import http.server
        import socketserver

        os.chdir(str(self.output_dir))
        handler = http.server.SimpleHTTPRequestHandler
        print(f"Docs site: http://{host}:{port}")
        with socketserver.TCPServer((host, port), handler) as httpd:
            httpd.serve_forever()
