"""
orchestra/mobile/offline_queue.py
----------------------------------
Offline-first request queue for Horizon Orchestra.

Provides:
- ``OfflineQueueJS``: generates the client-side IndexedDB queue JS
- ``OfflineQueueBackend``: Python FastAPI backend to receive batched queued requests
- ``register_routes(app)``: mounts the backend endpoint on a FastAPI app

The JS layer stores outgoing requests in IndexedDB when offline and
auto-replays them when connectivity is restored.  Priority levels allow
user messages to be replayed before analytics events.
"""
from __future__ import annotations

__all__ = [
    "OfflineQueueJS",
    "OfflineQueueBackend",
    "QueuedRequest",
    "QueuePriority",
    "register_routes",
]

import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

logger = logging.getLogger("orchestra.mobile.offline_queue")


# ---------------------------------------------------------------------------
# Enums / data classes (Python-side)
# ---------------------------------------------------------------------------


class QueuePriority(str, Enum):
    """Priority levels for queued offline requests."""

    HIGH = "high"      # User messages — replayed first
    MEDIUM = "medium"  # File uploads
    LOW = "low"        # Analytics, telemetry


@dataclass
class QueuedRequest:
    """Represents a single serialised request in the offline queue."""

    url: str
    method: str = "POST"
    headers: dict[str, str] = field(default_factory=dict)
    body: str | None = None
    priority: QueuePriority = QueuePriority.HIGH
    timestamp: float = field(default_factory=time.time)
    status: str = "pending"   # pending | sending | sent | failed
    retries: int = 0
    max_retries: int = 3
    queue_id: str | None = None  # set by the backend on receipt


# ---------------------------------------------------------------------------
# Client-side JS generator
# ---------------------------------------------------------------------------


class OfflineQueueJS:
    """Generates the IndexedDB-backed offline queue JavaScript.

    Usage::

        js = OfflineQueueJS().build()
    """

    DB_NAME = "horizon-offline-queue"
    DB_VERSION = 1
    STORE_NAME = "requests"
    MAX_STORAGE_BYTES = 50 * 1024 * 1024  # 50 MB
    MAX_RETRIES = 3
    BACKOFF_BASE_MS = 1_000

    def build(self) -> str:
        """Return the complete offline queue JS module."""
        return f"""\
// ============================================================
// Horizon Orchestra — Offline Queue (IndexedDB)
// Auto-generated by orchestra.mobile.offline_queue
// ============================================================

'use strict';

const _DB_NAME    = '{self.DB_NAME}';
const _DB_VERSION = {self.DB_VERSION};
const _STORE      = '{self.STORE_NAME}';
const MAX_BYTES   = {self.MAX_STORAGE_BYTES};
const MAX_RETRIES = {self.MAX_RETRIES};
const BACKOFF_MS  = {self.BACKOFF_BASE_MS};

// Priority ordering — lower number = higher priority
const PRIORITY_ORDER = {{ high: 0, medium: 1, low: 2 }};

// ---- DB initialisation ----

function openDB() {{
  return new Promise((resolve, reject) => {{
    const req = indexedDB.open(_DB_NAME, _DB_VERSION);
    req.onupgradeneeded = (e) => {{
      const db = e.target.result;
      if (!db.objectStoreNames.contains(_STORE)) {{
        const store = db.createObjectStore(_STORE, {{ keyPath: 'id', autoIncrement: true }});
        store.createIndex('status',    'status',    {{ unique: false }});
        store.createIndex('priority',  'priority',  {{ unique: false }});
        store.createIndex('timestamp', 'timestamp', {{ unique: false }});
      }}
    }};
    req.onsuccess = (e) => resolve(e.target.result);
    req.onerror   = (e) => reject(e.target.error);
  }});
}}

function idbRequest(req) {{
  return new Promise((res, rej) => {{
    req.onsuccess = (e) => res(e.target.result);
    req.onerror   = (e) => rej(e.target.error);
  }});
}}

// ============================================================
// OfflineQueue — public API
// ============================================================

export class OfflineQueue {{
  /**
   * Offline-first request queue backed by IndexedDB.
   *
   * @param {{string}} syncEndpoint  URL to POST batched requests to when online
   */
  constructor(syncEndpoint = '/api/mobile/queue/sync') {{
    this._endpoint = syncEndpoint;
    this._syncing  = false;
    this._db       = null;

    // Wire up online/offline events
    window.addEventListener('online',  () => this._onOnline());
    window.addEventListener('offline', () => console.log('[Queue] Device is offline'));

    // Attempt sync on construction if already online
    if (navigator.onLine) this._scheduleSync(0);
  }}

  // ---- Public methods ----

  /** Enqueue a request.  Returns the new item id. */
  async enqueue(url, method = 'POST', headers = {{}}, body = null, priority = 'high') {{
    await this._ensureDB();
    await this._enforceStorageLimit(priority);

    const item = {{
      url, method, headers, body,
      priority,
      timestamp: Date.now(),
      status:    'pending',
      retries:   0,
    }};

    const db = this._db;
    const tx = db.transaction(_STORE, 'readwrite');
    const id = await idbRequest(tx.objectStore(_STORE).add(item));
    console.log('[Queue] Enqueued:', url, 'priority:', priority, 'id:', id);
    return id;
  }}

  /** Dequeue (remove and return) the highest-priority pending item. */
  async dequeue() {{
    await this._ensureDB();
    const all = await this._getByStatus('pending');
    if (!all.length) return null;

    all.sort((a, b) => {{
      const pa = PRIORITY_ORDER[a.priority] ?? 9;
      const pb = PRIORITY_ORDER[b.priority] ?? 9;
      return pa !== pb ? pa - pb : a.timestamp - b.timestamp;
    }});

    const item = all[0];
    const db = this._db;
    const tx = db.transaction(_STORE, 'readwrite');
    tx.objectStore(_STORE).delete(item.id);
    return item;
  }}

  /** Peek at the next item without removing it. */
  async peek() {{
    const item = await this.dequeue();
    if (!item) return null;
    await this.enqueue(item.url, item.method, item.headers, item.body, item.priority);
    return item;
  }}

  /** Return the number of items currently in the queue. */
  async size() {{
    await this._ensureDB();
    const db = this._db;
    const tx = db.transaction(_STORE, 'readonly');
    return idbRequest(tx.objectStore(_STORE).count());
  }}

  /** Clear all items from the queue. */
  async clear() {{
    await this._ensureDB();
    const db = this._db;
    const tx = db.transaction(_STORE, 'readwrite');
    return idbRequest(tx.objectStore(_STORE).clear());
  }}

  /** Get all items grouped by status. */
  async getAll() {{
    await this._ensureDB();
    const db = this._db;
    const tx = db.transaction(_STORE, 'readonly');
    return idbRequest(tx.objectStore(_STORE).getAll());
  }}

  // ---- Sync ----

  /** Manually trigger a sync attempt. */
  async sync() {{
    if (!navigator.onLine) {{ console.log('[Queue] Offline — sync deferred'); return; }}
    if (this._syncing)     {{ console.log('[Queue] Sync already in progress'); return; }}

    this._syncing = true;
    try {{
      await this._replayAll();
    }} finally {{
      this._syncing = false;
    }}
  }}

  // ---- Private ----

  async _ensureDB() {{
    if (!this._db) this._db = await openDB();
  }}

  _onOnline() {{
    console.log('[Queue] Device online — scheduling sync');
    this._scheduleSync(500);
  }}

  _scheduleSync(delayMs) {{
    setTimeout(() => this.sync(), delayMs);
  }}

  async _replayAll() {{
    const pending = await this._getByStatus('pending');
    if (!pending.length) return;

    // Sort by priority then timestamp
    pending.sort((a, b) => {{
      const pa = PRIORITY_ORDER[a.priority] ?? 9;
      const pb = PRIORITY_ORDER[b.priority] ?? 9;
      return pa !== pb ? pa - pb : a.timestamp - b.timestamp;
    }});

    // Batch by priority group and POST to backend
    const batches = {{}};
    for (const item of pending) {{
      (batches[item.priority] = batches[item.priority] || []).push(item);
    }}

    for (const [priority, items] of Object.entries(batches)) {{
      await this._sendBatch(items, priority);
    }}
  }}

  async _sendBatch(items, priority) {{
    await this._markAll(items, 'sending');
    try {{
      const resp = await fetch(this._endpoint, {{
        method:  'POST',
        headers: {{ 'Content-Type': 'application/json' }},
        body: JSON.stringify({{ priority, requests: items }}),
      }});

      if (resp.ok) {{
        const result = await resp.json();
        for (const item of items) {{
          await this._updateStatus(item.id, 'sent');
        }}
        console.log('[Queue] Batch sent OK — priority:', priority, 'count:', items.length);
      }} else {{
        await this._handleBatchError(items, `HTTP ${{resp.status}}`);
      }}
    }} catch (err) {{
      await this._handleBatchError(items, String(err));
    }}
  }}

  async _handleBatchError(items, reason) {{
    for (const item of items) {{
      const retries = (item.retries || 0) + 1;
      if (retries >= MAX_RETRIES) {{
        await this._updateStatus(item.id, 'failed', retries);
        console.warn('[Queue] Item permanently failed:', item.url, reason);
      }} else {{
        await this._updateStatus(item.id, 'pending', retries);
        const backoff = BACKOFF_MS * Math.pow(2, retries - 1);
        console.log('[Queue] Will retry item', item.id, 'in', backoff, 'ms');
        setTimeout(() => this.sync(), backoff);
      }}
    }}
  }}

  async _markAll(items, status) {{
    for (const item of items) {{
      await this._updateStatus(item.id, status);
    }}
  }}

  async _updateStatus(id, status, retries = undefined) {{
    await this._ensureDB();
    const db = this._db;
    const tx = db.transaction(_STORE, 'readwrite');
    const store = tx.objectStore(_STORE);
    const item = await idbRequest(store.get(id));
    if (!item) return;
    item.status = status;
    if (retries !== undefined) item.retries = retries;
    store.put(item);
  }}

  async _getByStatus(status) {{
    await this._ensureDB();
    const db = this._db;
    const tx = db.transaction(_STORE, 'readonly');
    const idx = tx.objectStore(_STORE).index('status');
    return idbRequest(idx.getAll(IDBKeyRange.only(status)));
  }}

  async _enforceStorageLimit(incomingPriority) {{
    // Evict oldest low-priority items when storage is near the limit
    if (incomingPriority === 'high') return; // never evict for high priority

    try {{
      if (navigator.storage && navigator.storage.estimate) {{
        const {{ usage }} = await navigator.storage.estimate();
        if (usage < MAX_BYTES) return;
      }}
    }} catch {{ return; }}

    const low = await this._getByStatus('pending');
    const toEvict = low.filter((i) => i.priority === 'low');
    toEvict.sort((a, b) => a.timestamp - b.timestamp); // oldest first

    const db = this._db;
    for (const item of toEvict.slice(0, 10)) {{
      const tx = db.transaction(_STORE, 'readwrite');
      tx.objectStore(_STORE).delete(item.id);
      console.log('[Queue] Evicted low-priority item:', item.id);
    }}
  }}
}}

// Export a singleton for easy import
export const horizonQueue = new OfflineQueue();
"""


# ---------------------------------------------------------------------------
# Python backend
# ---------------------------------------------------------------------------


class OfflineQueueBackend:
    """Python backend that receives and processes batched queued requests.

    The JS client POSTs a JSON body::

        {
            "priority": "high",
            "requests": [
                { "url": "/api/chat", "method": "POST",
                  "headers": {...}, "body": "...", ... }
            ]
        }

    The backend replays each request internally and returns a result
    summary to the client.
    """

    def __init__(self, forward_base_url: str = "") -> None:
        """
        Args:
            forward_base_url: Optional base URL to forward requests to.
                              If empty, requests are processed in-process.
        """
        self._base_url = forward_base_url.rstrip("/")

    async def process_batch(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Process a batch of queued requests.

        Returns a summary dict with counts of succeeded and failed replays.
        """
        priority: str = payload.get("priority", "high")
        requests: list[dict] = payload.get("requests", [])
        succeeded = 0
        failed = 0
        errors: list[str] = []

        logger.info(
            "offline_queue: received batch priority=%s count=%d",
            priority,
            len(requests),
        )

        for req in requests:
            try:
                result = await self._replay_request(req)
                if result:
                    succeeded += 1
                else:
                    failed += 1
                    errors.append(f"replay failed for {req.get('url')}")
            except Exception as exc:
                failed += 1
                errors.append(str(exc))
                logger.warning("offline_queue: replay error for %s: %s", req.get("url"), exc)

        return {
            "priority": priority,
            "total": len(requests),
            "succeeded": succeeded,
            "failed": failed,
            "errors": errors,
            "timestamp": time.time(),
        }

    async def _replay_request(self, req: dict[str, Any]) -> bool:
        """Replay a single queued request.

        Returns True on success, False on failure.
        """
        import asyncio

        url: str = req.get("url", "")
        method: str = req.get("method", "POST").upper()
        headers: dict = req.get("headers", {})
        body: str | None = req.get("body")

        if not url:
            logger.warning("offline_queue: skipping request with empty URL")
            return False

        # If forwarding to an upstream service
        if self._base_url and not url.startswith("http"):
            url = f"{self._base_url}{url}"

        try:
            import httpx

            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.request(
                    method=method,
                    url=url,
                    headers=headers,
                    content=body.encode() if body else None,
                )
                logger.debug(
                    "offline_queue: replayed %s %s -> %d", method, url, response.status_code
                )
                return response.is_success
        except ImportError:
            # httpx not available — log and pretend success for development
            logger.warning(
                "httpx not installed; cannot replay %s %s. Install with: pip install httpx",
                method,
                url,
            )
            return True
        except Exception as exc:
            logger.error("offline_queue: replay error %s %s: %s", method, url, exc)
            return False


# ---------------------------------------------------------------------------
# FastAPI route registration
# ---------------------------------------------------------------------------


def register_routes(app: Any) -> None:
    """Register offline queue backend routes on a FastAPI application instance.

    Registers:
        POST /api/mobile/queue/sync  — receives batched queued requests
        GET  /api/mobile/queue/js    — serves the offline queue JS module
    """
    try:
        from fastapi import Request
        from fastapi.responses import JSONResponse, Response
    except ImportError:  # pragma: no cover — optional web dependency
        logger.warning("FastAPI not installed; offline queue routes not registered")
        return

    backend = OfflineQueueBackend()
    js_generator = OfflineQueueJS()

    @app.post("/api/mobile/queue/sync", include_in_schema=True)
    async def sync_queue(request: Request) -> JSONResponse:
        """Receive and replay a batch of queued offline requests."""
        try:
            payload = await request.json()
        except Exception:
            return JSONResponse({"error": "invalid JSON"}, status_code=400)

        result = await backend.process_batch(payload)
        return JSONResponse(result)

    @app.get("/api/mobile/queue/js", include_in_schema=False)
    async def serve_queue_js() -> Response:
        """Serve the IndexedDB offline queue JavaScript module."""
        js = js_generator.build()
        return Response(
            content=js,
            media_type="application/javascript",
            headers={"Cache-Control": "public, max-age=3600"},
        )

    logger.info(
        "offline queue routes registered: POST /api/mobile/queue/sync, GET /api/mobile/queue/js"
    )
