"""
orchestra/mobile/service_worker.py
-----------------------------------
Service worker JavaScript generator and FastAPI routes for Horizon Orchestra.

Generates a full-featured service worker (sw.js) supporting:
- Cache-first, network-first, and stale-while-revalidate strategies
- App shell precaching with versioned cache names
- Runtime caching of API responses with 5-minute TTL
- Background sync for failed requests
- Push notification handling
- Periodic background sync for data refresh
- Automatic cache cleanup on activation
"""
from __future__ import annotations

__all__ = [
    "ServiceWorkerGenerator",
    "ServiceWorkerConfig",
    "generate_service_worker",
    "register_routes",
]

import logging
from dataclasses import dataclass, field

logger = logging.getLogger("orchestra.mobile.service_worker")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_DEFAULT_CACHE_VERSION = "v1"
_DEFAULT_API_CACHE_TTL_SECONDS = 300  # 5 minutes

_DEFAULT_PRECACHE_URLS: list[str] = [
    "/",
    "/offline",
    "/static/css/main.css",
    "/static/js/main.js",
    "/static/fonts/inter-var.woff2",
    "/manifest.json",
]

_DEFAULT_STATIC_PATTERNS: list[str] = [
    r"/static/",
    r"\.css$",
    r"\.js$",
    r"\.woff2?$",
    r"\.ttf$",
    r"\.png$",
    r"\.jpg$",
    r"\.svg$",
    r"\.ico$",
]

_DEFAULT_API_PATTERNS: list[str] = [
    r"/api/",
    r"/chat",
    r"/tasks",
    r"/stream",
]


@dataclass
class ServiceWorkerConfig:
    """Configuration for service worker generation."""

    cache_version: str = _DEFAULT_CACHE_VERSION
    app_name: str = "horizon-orchestra"
    api_cache_ttl_seconds: int = _DEFAULT_API_CACHE_TTL_SECONDS
    precache_urls: list[str] = field(default_factory=lambda: list(_DEFAULT_PRECACHE_URLS))
    static_patterns: list[str] = field(default_factory=lambda: list(_DEFAULT_STATIC_PATTERNS))
    api_patterns: list[str] = field(default_factory=lambda: list(_DEFAULT_API_PATTERNS))
    enable_background_sync: bool = True
    enable_periodic_sync: bool = True
    enable_push: bool = True
    offline_page: str = "/offline"
    bg_sync_tag: str = "horizon-sync-queue"
    periodic_sync_tag: str = "horizon-periodic-refresh"


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


class ServiceWorkerGenerator:
    """Generates the service worker JavaScript for Horizon Orchestra.

    Usage::

        gen = ServiceWorkerGenerator()
        js_code = gen.build()
    """

    def __init__(self, config: ServiceWorkerConfig | None = None) -> None:
        self.config = config or ServiceWorkerConfig()

    def build(self) -> str:
        """Build and return the complete service worker JS as a string."""
        cfg = self.config
        parts: list[str] = [
            self._section_constants(),
            self._section_install(),
            self._section_activate(),
            self._section_fetch(),
            self._section_background_sync() if cfg.enable_background_sync else "",
            self._section_push() if cfg.enable_push else "",
            self._section_periodic_sync() if cfg.enable_periodic_sync else "",
            self._section_helpers(),
        ]
        js = "\n\n".join(p for p in parts if p)
        logger.debug("service worker JS generated (%d chars)", len(js))
        return js

    # ------------------------------------------------------------------
    # JS sections
    # ------------------------------------------------------------------

    def _section_constants(self) -> str:
        cfg = self.config
        precache_json = _js_array(cfg.precache_urls)
        static_patterns = _js_array(cfg.static_patterns)
        api_patterns = _js_array(cfg.api_patterns)
        return f"""\
// ============================================================
// Horizon Orchestra — Service Worker {cfg.cache_version}
// Auto-generated by orchestra.mobile.service_worker
// ============================================================

'use strict';

const CACHE_VERSION = '{cfg.cache_version}';
const APP_NAME      = '{cfg.app_name}';
const CACHE_STATIC  = `${{APP_NAME}}-static-${{CACHE_VERSION}}`;
const CACHE_DYNAMIC = `${{APP_NAME}}-dynamic-${{CACHE_VERSION}}`;
const CACHE_API     = `${{APP_NAME}}-api-${{CACHE_VERSION}}`;
const OFFLINE_PAGE  = '{cfg.offline_page}';
const API_CACHE_TTL = {cfg.api_cache_ttl_seconds} * 1000; // ms
const BG_SYNC_TAG   = '{cfg.bg_sync_tag}';

const PRECACHE_URLS = {precache_json};

const STATIC_PATTERNS = {static_patterns}.map(p => new RegExp(p));
const API_PATTERNS    = {api_patterns}.map(p => new RegExp(p));"""

    def _section_install(self) -> str:
        return """\
// ============================================================
// Install — precache app shell
// ============================================================

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_STATIC).then(async (cache) => {
      console.log('[SW] Precaching app shell...');
      await cache.addAll(PRECACHE_URLS);
      console.log('[SW] App shell cached.');
    }).catch((err) => {
      console.error('[SW] Precache failed:', err);
    })
  );
  self.skipWaiting();
});"""

    def _section_activate(self) -> str:
        return """\
// ============================================================
// Activate — clean stale caches
// ============================================================

self.addEventListener('activate', (event) => {
  const VALID_CACHES = new Set([CACHE_STATIC, CACHE_DYNAMIC, CACHE_API]);

  event.waitUntil(
    caches.keys().then(async (cacheNames) => {
      const deletions = cacheNames
        .filter((name) => !VALID_CACHES.has(name))
        .map((name) => {
          console.log('[SW] Deleting stale cache:', name);
          return caches.delete(name);
        });
      await Promise.all(deletions);
      await self.clients.claim();
      console.log('[SW] Activated, clients claimed.');
    })
  );
});"""

    def _section_fetch(self) -> str:
        return """\
// ============================================================
// Fetch — routing strategies
// ============================================================

self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Skip non-GET for caching (POST etc. handled by background sync)
  if (request.method !== 'GET') return;

  // Skip chrome-extension and non-http(s)
  if (!url.protocol.startsWith('http')) return;

  if (isStaticAsset(url.pathname)) {
    event.respondWith(cacheFirst(request, CACHE_STATIC));
  } else if (isApiCall(url.pathname)) {
    event.respondWith(networkFirstWithApiCache(request));
  } else {
    event.respondWith(staleWhileRevalidate(request, CACHE_DYNAMIC));
  }
});

// ---- Cache-first strategy (static assets) ----

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  if (cached) return cached;

  try {
    const response = await fetch(request);
    if (response.ok) cache.put(request, response.clone());
    return response;
  } catch {
    const offline = await caches.match(OFFLINE_PAGE);
    return offline || new Response('Offline', { status: 503 });
  }
}

// ---- Network-first strategy (API calls) ----

async function networkFirstWithApiCache(request) {
  const cache = await caches.open(CACHE_API);
  const cacheKey = request.url;

  try {
    const response = await fetch(request);
    if (response.ok) {
      const timestamped = addTimestamp(response.clone());
      cache.put(cacheKey, timestamped);
    }
    return response;
  } catch {
    const cached = await cache.match(cacheKey);
    if (cached && !isCacheExpired(cached, API_CACHE_TTL)) {
      console.log('[SW] Serving stale API response from cache:', cacheKey);
      return cached;
    }
    return new Response(
      JSON.stringify({ error: 'offline', cached: false }),
      { status: 503, headers: { 'Content-Type': 'application/json' } }
    );
  }
}

// ---- Stale-while-revalidate strategy ----

async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);

  const fetchPromise = fetch(request).then((response) => {
    if (response.ok) cache.put(request, response.clone());
    return response;
  }).catch(() => null);

  if (cached) return cached;

  try {
    const response = await fetchPromise;
    if (response) return response;
  } catch { /* fall through */ }

  const offline = await caches.match(OFFLINE_PAGE);
  return offline || new Response('Offline', { status: 503 });
}"""

    def _section_background_sync(self) -> str:
        return """\
// ============================================================
// Background Sync — replay queued requests when back online
// ============================================================

self.addEventListener('sync', (event) => {
  if (event.tag === BG_SYNC_TAG) {
    console.log('[SW] Background sync triggered:', event.tag);
    event.waitUntil(replayQueue());
  }
});

async function replayQueue() {
  const db = await openQueueDB();
  const tx = db.transaction('requests', 'readwrite');
  const store = tx.objectStore('requests');
  const all = await promisifyRequest(store.getAll());

  for (const item of all) {
    if (item.status !== 'pending') continue;
    try {
      const response = await fetch(new Request(item.url, {
        method: item.method,
        headers: item.headers,
        body: item.body || null,
      }));
      if (response.ok) {
        const delTx = db.transaction('requests', 'readwrite');
        delTx.objectStore('requests').delete(item.id);
        console.log('[SW] Replayed queued request:', item.url);
      } else {
        await markFailed(db, item.id, `HTTP ${response.status}`);
      }
    } catch (err) {
      await markFailed(db, item.id, String(err));
    }
  }
}

async function markFailed(db, id, reason) {
  const tx = db.transaction('requests', 'readwrite');
  const store = tx.objectStore('requests');
  const item = await promisifyRequest(store.get(id));
  if (item) {
    item.status = 'failed';
    item.lastError = reason;
    item.retries = (item.retries || 0) + 1;
    store.put(item);
  }
}"""

    def _section_push(self) -> str:
        return """\
// ============================================================
// Push Notifications
// ============================================================

self.addEventListener('push', (event) => {
  let payload = { title: 'Horizon Orchestra', body: 'You have a new update', type: 'default' };

  if (event.data) {
    try { payload = { ...payload, ...event.data.json() }; }
    catch { payload.body = event.data.text(); }
  }

  const icon = '/static/icons/icon-192.png';
  const badge = '/static/icons/badge-72.png';

  const options = {
    body: payload.body,
    icon,
    badge,
    tag: payload.tag || payload.type || 'horizon-notification',
    renotify: false,
    requireInteraction: payload.type === 'error',
    silent: false,
    data: payload,
    actions: buildNotificationActions(payload.type),
    vibrate: [100, 50, 100],
  };

  event.waitUntil(
    self.registration.showNotification(payload.title || 'Horizon Orchestra', options)
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const payload = event.notification.data || {};
  const action = event.action;

  let targetUrl = '/';
  if (action === 'view' || !action) {
    targetUrl = payload.url || '/tasks';
  } else if (action === 'reply') {
    targetUrl = payload.replyUrl || '/chat/new';
  } else if (action === 'dismiss') {
    return; // just close
  }

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url === targetUrl && 'focus' in client) return client.focus();
      }
      if (clients.openWindow) return clients.openWindow(targetUrl);
    })
  );
});

self.addEventListener('notificationclose', (event) => {
  const payload = event.notification.data || {};
  // Track dismissal analytics if needed
  console.log('[SW] Notification dismissed:', payload.type);
});

function buildNotificationActions(type) {
  const VIEW   = { action: 'view',    title: 'View'    };
  const REPLY  = { action: 'reply',   title: 'Reply'   };
  const DISMISS = { action: 'dismiss', title: 'Dismiss' };

  switch (type) {
    case 'task_complete':  return [VIEW, DISMISS];
    case 'task_progress':  return [VIEW, DISMISS];
    case 'mention':        return [REPLY, VIEW, DISMISS];
    case 'daily_briefing': return [VIEW, DISMISS];
    case 'error':          return [VIEW, DISMISS];
    default:               return [VIEW, DISMISS];
  }
}"""

    def _section_periodic_sync(self) -> str:
        return """\
// ============================================================
// Periodic Background Sync
// ============================================================

self.addEventListener('periodicsync', (event) => {
  if (event.tag === 'horizon-periodic-refresh') {
    console.log('[SW] Periodic sync triggered');
    event.waitUntil(periodicRefresh());
  }
});

async function periodicRefresh() {
  try {
    const response = await fetch('/api/briefing/refresh', { method: 'POST' });
    if (response.ok) {
      console.log('[SW] Periodic data refresh complete');
    }
  } catch (err) {
    console.warn('[SW] Periodic refresh failed:', err);
  }
}"""

    def _section_helpers(self) -> str:
        return """\
// ============================================================
// Helpers
// ============================================================

function isStaticAsset(pathname) {
  return STATIC_PATTERNS.some((re) => re.test(pathname));
}

function isApiCall(pathname) {
  return API_PATTERNS.some((re) => re.test(pathname));
}

function addTimestamp(response) {
  const headers = new Headers(response.headers);
  headers.append('X-SW-Cached-At', Date.now().toString());
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

function isCacheExpired(response, ttlMs) {
  const cachedAt = response.headers.get('X-SW-Cached-At');
  if (!cachedAt) return true;
  return Date.now() - parseInt(cachedAt, 10) > ttlMs;
}

// Minimal IndexedDB helper for background sync queue
function openQueueDB() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open('horizon-offline-queue', 1);
    req.onupgradeneeded = (e) => {
      const db = e.target.result;
      if (!db.objectStoreNames.contains('requests')) {
        const store = db.createObjectStore('requests', { keyPath: 'id', autoIncrement: true });
        store.createIndex('status', 'status', { unique: false });
        store.createIndex('priority', 'priority', { unique: false });
      }
    };
    req.onsuccess = (e) => resolve(e.target.result);
    req.onerror = (e) => reject(e.target.error);
  });
}

function promisifyRequest(req) {
  return new Promise((resolve, reject) => {
    req.onsuccess = (e) => resolve(e.target.result);
    req.onerror = (e) => reject(e.target.error);
  });
}"""


# ---------------------------------------------------------------------------
# Convenience wrapper
# ---------------------------------------------------------------------------


def generate_service_worker(config: ServiceWorkerConfig | None = None) -> str:
    """Generate and return the service worker JS string."""
    return ServiceWorkerGenerator(config).build()


# ---------------------------------------------------------------------------
# FastAPI route registration
# ---------------------------------------------------------------------------


def register_routes(app: object) -> None:
    """Register service worker routes on a FastAPI application instance.

    Registers:
        GET /sw.js  — service worker JS with correct MIME type and scope header
    """
    try:
        from fastapi.responses import Response
    except ImportError:  # pragma: no cover — optional web dependency
        logger.warning("FastAPI not installed; service worker routes not registered")
        return

    @app.get("/sw.js", include_in_schema=False)
    async def serve_service_worker() -> Response:
        """Serve the service worker JavaScript."""
        js_content = generate_service_worker()
        return Response(
            content=js_content,
            media_type="application/javascript",
            headers={
                "Service-Worker-Allowed": "/",
                "Cache-Control": "no-cache, no-store, must-revalidate",
                "X-Content-Type-Options": "nosniff",
            },
        )

    logger.info("service worker route registered: /sw.js")


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _js_array(items: list[str]) -> str:
    """Format a Python list of strings as a JS array literal."""
    lines = [f"  '{item}'" for item in items]
    return "[\n" + ",\n".join(lines) + "\n]"
