{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "orchestra.fullname" . }}
  labels:
    {{- include "orchestra.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
{{- if and .Values.ollama.enabled .Values.ollama.persistentVolume.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "orchestra.fullname" . }}-ollama
  labels:
    {{- include "orchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.persistentVolume.size | quote }}
  {{- with .Values.ollama.persistentVolume.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
